### ISSUE TITLE
Create Set Password Page

### ISSUE THREAD

**Issue by intechgration-x** [in-tech-gration/kiptrak-cloud#1]
- When the user receives an invite link, they must be able to land on a Set Password page after clicking the `Accept Invite` link in order to configure their password.
- If you accept the challenge, (1) create a new branch, (2) assign yourself to the Issue and (3) leave a comment below.

[Relevant details](https://github.com/orgs/supabase/discussions/3208#discussioncomment-1331469)

**Comment by kostasx** [comment]
Work in progress...

**Comment by asterisg** [comment]
I've changed the template on the invitation link send from Supabase, to use the `{{ .ConfirmationURL }}` instead of the `{{ .RedirectTo }}` that was before. I've kept the `/password` since the link given ends with `https://kiptrak.netlify.app`.
All the above can be configured via the Supabase Dashboard (Authentication -> Email Templates under Configuration pane)

I've succeffully created a temporary user using a [temporay email address](https://temp-mail.org/en).
Are there any issues left?
